I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cabin.rpy", line 48, in script
Exception: Sayer 'b' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Sko\Desktop\renpy-6.15.7-sdk\renpy\execution.py", line 288, in run
    node.execute()
  File "C:\Users\Sko\Desktop\renpy-6.15.7-sdk\renpy\ast.py", line 431, in execute
    raise Exception("Sayer '%s' is not defined." % self.who.encode("utf-8"))
Exception: Sayer 'b' is not defined.

Windows-7-6.1.7601-SP1
Ren'Py 6.15.7.374
A Ren'Py Game 0.0
